set(BUILD_RELEASE False)
if (NOT CMAKE_BUILD_TYPE OR CMAKE_BUILD_TYPE STREQUAL "None")
    set(CMAKE_BUILD_TYPE "Debug")
    message(STATUS "CMAKE_BUILD_TYPE is not set, set to default = ${CMAKE_BUILD_TYPE}")
    message(STATUS "Project Build Type:${CMAKE_BUILD_TYPE}")
else()
    string(TOUPPER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_UPPER_STR)
    if(${CMAKE_BUILD_TYPE_UPPER_STR} STREQUAL "DEBUG")
        message(STATUS "Project Build Type:${CMAKE_BUILD_TYPE}")
    elseif(${CMAKE_BUILD_TYPE_UPPER_STR} STREQUAL "RELEASE")
        set(BUILD_RELEASE True)
        message(STATUS "Project Build Type:${CMAKE_BUILD_TYPE}")
    else()
        set(${CMAKE_BUILD_TYPE} "Debug")
        message(STATUS "Project Build Type:${CMAKE_BUILD_TYPE}")
    endif()
endif()